name: Valgrind

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'alim/**'
    - 'meca/**'
    - 'reunion/**'

jobs:

   ValgrindCheckProject :
    runs-on: ubuntu-latest
    steps :
      - uses: codecov/codecov-action@v1
      - uses : actions/checkout@v2
      - name : valgrind build
        run: |
          sudo apt-get install -y valgrind
          cd code
          mkdir build
          cd build
          cmake .. 
          make code
          valgrind ./bin/project
          
   ValgrindCheckTest :
    runs-on: ubuntu-latest
    steps :
    - uses: codecov/codecov-action@v1
    - uses : actions/checkout@v2
    - name : valgrind build
      run: |
        sudo apt-get install -y valgrind
        cd code
        mkdir build
        cd build
        cmake .. 
        make code
        valgrind ./code/build/bin/test
      

